global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: n42 # example, how to connect prometheus to n42
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets:
          - 172.18.0.2:6060
#          - bootnode:6061
#          - bootnode:6062
#          - host.docker.internal:6060 # this is how docker-for-mac allow to access host machine
#          - host.docker.internal:6061
#          - host.docker.internal:6062
#          - 192.168.255.134:6060
#          - 192.168.255.134:6061
#          - 192.168.255.134:6062
#          - 192.168.255.138:6060
#          - 192.168.255.138:6061
#          - 192.168.255.138:6062

#  - job_name: n42-openmetrics # this job collecting metrics in OpenMetrics format
#    metrics_path: /debug/metrics/prometheus2
#    scheme: http
#    static_configs:
#      - targets:
#          - n42:6060
#          - n42:6061
#          - n42:6062
#          - host.docker.internal:6060
#          - host.docker.internal:6061
#          - host.docker.internal:6062
#          - 192.168.255.134:6060
#          - 192.168.255.134:6061
#          - 192.168.255.134:6062
#          - 192.168.255.138:6060
#          - 192.168.255.138:6061
#          - 192.168.255.138:6062
